sudo: required
services:
 - docker

before_install:
 - docker build -t tomislavstojanov/docker-react -f Dockerfile.dev .

script:
 - docker run tomislavstojanov/docker-react npm run test -- --coverage
